spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      
logging:
  level:
    com.financiero: WARN
    org.springframework: WARN
    org.hibernate: WARN